s

diff --git a/foundryup-zksync b/foundryup-zksync
--- a/foundryup-zksync
+++ b/foundryup-zksync
@@ -1,10 +1,18 @@
 #!/usr/bin/env bash
 set -eo pipefail
 
+# NOTE: if you make modifications to this script, please increment the version number.
+# Major / minor: incremented for each stable release of Foundry.
+# Patch: incremented for each change between stable releases.
+FOUNDRYUP_INSTALLER_VERSION="1.0.1"
+
 BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
 FOUNDRY_DIR=${FOUNDRY_DIR:-"$BASE_DIR/.foundry"}
+FOUNDRY_VERSIONS_DIR="$FOUNDRY_DIR/versions"
 FOUNDRY_BIN_DIR="$FOUNDRY_DIR/bin"
 FOUNDRY_MAN_DIR="$FOUNDRY_DIR/share/man/man1"
+FOUNDRY_BIN_URL="https://raw.githubusercontent.com/foundry-rs/foundry/master/foundryup/foundryup"
+FOUNDRY_BIN_PATH="$FOUNDRY_BIN_DIR/foundryup"
 
 FOUNDRYUP_JOBS=""
 
@@ -20,9 +28,13 @@ main() {
     case $1 in
       --)               shift; break;;
 
+      -v|--version)     shift; version;;
+      -U|--update)      shift; update;;
       -r|--repo)        shift; FOUNDRYUP_REPO=$1;;
       -b|--branch)      shift; FOUNDRYUP_BRANCH=$1;;
-      -v|--version)     shift; FOUNDRYUP_VERSION=$1;;
+      -i|--install)     shift; FOUNDRYUP_VERSION=$1;;
+      -l|--list)        shift; list;;
+      -u|--use)         shift; FOUNDRYUP_VERSION=$1; use;;
       -p|--path)        shift; FOUNDRYUP_LOCAL_REPO=$1;;
       -P|--pr)          shift; FOUNDRYUP_PR=$1;;
       -C|--commit)      shift; FOUNDRYUP_COMMIT=$1;;
@@ -57,13 +69,15 @@ main() {
     fi
   fi
 
+  check_bins_in_use
+
   # Installs foundry from a local repository if --path parameter is provided
   if [[ -n "$FOUNDRYUP_LOCAL_REPO" ]]; then
     need_cmd cargo
 
     # Ignore branches/versions as we do not want to modify local git state
     if [ -n "$FOUNDRYUP_REPO" ] || [ -n "$FOUNDRYUP_BRANCH" ] || [ -n "$FOUNDRYUP_VERSION" ]; then
-      warn "--branch, --version, and --repo arguments are ignored during local install"
+      warn "--branch, --install, --use, and --repo arguments are ignored during local install"
     fi
 
     # Enter local repo and build
@@ -148,45 +162,36 @@ main() {
     fi
 
     # Compute the URL of the release tarball in the Foundry repository.
+    ARCHIVE_TAG=$(echo "$FOUNDRYUP_TAG" | tr '-' '_')
     RELEASE_URL="https://github.com/${FOUNDRYUP_REPO}/releases/download/${FOUNDRYUP_TAG}/"
-    BIN_ARCHIVE_URL="${RELEASE_URL}foundry_nightly_${PLATFORM}_${ARCHITECTURE}.$EXT"
+    BIN_ARCHIVE_URL="${RELEASE_URL}${ARCHIVE_TAG}_${PLATFORM}_${ARCHITECTURE}.$EXT"
+    MAN_TAG=$(echo "$FOUNDRYUP_TAG" | sed 's/^foundry-zksync-//')
+    MAN_TARBALL_URL="${RELEASE_URL}foundry_zksync_man_${MAN_TAG}.tar.gz"
     
     # Download and extract the binaries archive
     say "downloading latest forge, and cast"
     if [ "$PLATFORM" = "win32" ]; then
       tmp="$(mktemp -d 2>/dev/null || echo ".")/foundry-zksync.zip"
       ensure download "$BIN_ARCHIVE_URL" "$tmp"
-      ensure unzip "$tmp" -d "$FOUNDRY_BIN_DIR"
+      ensure unzip "$tmp" -d "$FOUNDRY_VERSIONS_DIR/$FOUNDRYUP_TAG"
       rm -f "$tmp"
     else
-      ensure download "$BIN_ARCHIVE_URL" | ensure tar -xzC "$FOUNDRY_BIN_DIR"
+      ensure mkdir -p "$FOUNDRY_VERSIONS_DIR/$ARCHIVE_TAG"
+      ensure download "$BIN_ARCHIVE_URL" | ensure tar -xzC "$FOUNDRY_VERSIONS_DIR/$ARCHIVE_TAG"
     fi
 
     # Optionally download the manuals
     if check_cmd tar; then
-      say "attempting to download manpages from release assets"
+      say "downloading manpages"
       mkdir -p "$FOUNDRY_MAN_DIR"
-
-      ASSET_DATA=$(curl -s "https://api.github.com/repos/${FOUNDRYUP_REPO}/releases/tags/${FOUNDRYUP_TAG}")
-
-      # Parse out the man asset name:
-      # e.g. "foundry_man_nightly-ae913af65381734ad46c044a9495b67310bc77c4.tar.gz"
-      MAN_ASSET_NAME=$(echo "$ASSET_DATA" | grep -oE '"name":\s*"foundry_man_nightly[^"]+' \
-                                      | sed 's/"name": "//')
-
-      if [ -n "$MAN_ASSET_NAME" ]; then
-        MAN_TARBALL_URL="${RELEASE_URL}${MAN_ASSET_NAME}"
-        say "Found manpage tarball: $MAN_TARBALL_URL"
-        download "$MAN_TARBALL_URL" | tar -xzC "$FOUNDRY_MAN_DIR"
-      else
-        say "No manpage tarball found for this release."
-      fi
+      download "$MAN_TARBALL_URL" | tar -xzC "$FOUNDRY_MAN_DIR"
     else
       say 'skipping manpage download: missing "tar"'
     fi
 
     for bin in "${BINS[@]}"; do
       bin_path="$FOUNDRY_BIN_DIR/$bin"
+      cp $FOUNDRY_VERSIONS_DIR/$ARCHIVE_TAG/$bin $bin_path
 
       # Print installed msg
       say "installed - $(ensure "$bin_path" --version)"
@@ -276,10 +281,10 @@ EOF
     need_cmd cargo
     FOUNDRYUP_BRANCH=${FOUNDRYUP_BRANCH:-main}
     REPO_PATH="$FOUNDRY_DIR/$FOUNDRYUP_REPO"
+    AUTHOR="$(echo "$FOUNDRYUP_REPO" | cut -d'/' -f1 -)"
 
     # If repo path does not exist, grab the author from the repo, make a directory in .foundry, cd to it and clone.
     if [ ! -d "$REPO_PATH" ]; then
-      AUTHOR="$(echo "$FOUNDRYUP_REPO" | cut -d'/' -f1 -)"
       ensure mkdir -p "$FOUNDRY_DIR/$AUTHOR"
       cd "$FOUNDRY_DIR/$AUTHOR"
       ensure git clone "https://github.com/$FOUNDRYUP_REPO"
@@ -290,22 +295,38 @@ EOF
     ensure git fetch origin "${FOUNDRYUP_BRANCH}:remotes/origin/${FOUNDRYUP_BRANCH}"
     ensure git checkout "origin/${FOUNDRYUP_BRANCH}"
 
-    # If set, checkout specific commit from branch
+    # Create custom version based on the install method, e.g.:
+    # - foundry-rs-commit-c22c4cc96b0535cd989ee94b79da1b19d236b8db
+    # - foundry-rs-pr-1
+    # - foundry-rs-branch-chore-bump-forge-std
     if [ -n "$FOUNDRYUP_COMMIT" ]; then
-      say "installing at commit $FOUNDRYUP_COMMIT"
+      # If set, checkout specific commit from branch
       ensure git checkout "$FOUNDRYUP_COMMIT"
+      FOUNDRYUP_VERSION=$AUTHOR-commit-$FOUNDRYUP_COMMIT
+    elif [ -n "$FOUNDRYUP_PR" ]; then
+     FOUNDRYUP_VERSION=$AUTHOR-pr-$FOUNDRYUP_PR
+    else
+      if [ -n "$FOUNDRYUP_BRANCH" ]; then
+        NORMALIZED_BRANCH="$(echo "$FOUNDRYUP_BRANCH" | tr / -)"
+        FOUNDRYUP_VERSION=$AUTHOR-branch-$NORMALIZED_BRANCH
+      fi
     fi
+    say "installing version $FOUNDRYUP_VERSION"
 
-    # Build the repo and install the binaries locally to the .foundry bin directory.
+    # Build the repo.
     ensure cargo build --bins "${CARGO_BUILD_ARGS[@]}"
+    # Create foundry custom version directory.
+    ensure mkdir -p "$FOUNDRY_VERSIONS_DIR/$FOUNDRYUP_VERSION"
     for bin in "${BINS[@]}"; do
       for try_path in target/release/$bin target/release/$bin.exe; do
         if [ -f "$try_path" ]; then
-          [ -e "$FOUNDRY_BIN_DIR/$bin" ] && warn "overwriting existing $bin in $FOUNDRY_BIN_DIR"
-          mv -f "$try_path" "$FOUNDRY_BIN_DIR"
+          mv -f "$try_path" "$FOUNDRY_VERSIONS_DIR/$FOUNDRYUP_VERSION"
         fi
       done
     done
+
+    # Use newly built version.
+    use
 
     # If help2man is installed, use it to add Foundry man pages.
     if check_cmd help2man; then
@@ -324,14 +345,18 @@ The installer for Foundry-zksync.
 
 Update or revert to a specific Foundry-zksync version with ease.
 
-By default, the latest nightly version is installed from built binaries.
+By default, the latest stable version is installed from built binaries.
 
 USAGE:
     foundryup-zksync <OPTIONS>
 
 OPTIONS:
     -h, --help      Print help information
-    -v, --version   Install a specific version from built binaries
+    -v, --version   Print the version of foundryup
+    -U, --update    Update foundryup to the latest version
+    -i, --install   Install a specific version from built binaries
+    -l, --list      List versions installed from built binaries
+    -u, --use       Use a specific installed version from built binaries
     -b, --branch    Build and install a specific branch
     -P, --pr        Build and install a specific Pull Request
     -C, --commit    Build and install a specific commit
@@ -341,6 +366,78 @@ OPTIONS:
     --arch          Install a specific architecture (supports amd64 and arm64)
     --platform      Install a specific platform (supports win32, linux, and darwin)
 EOF
+}
+
+version() {
+  say "$FOUNDRYUP_INSTALLER_VERSION"
+  exit 0
+}
+
+update() {
+  say "updating foundryup..."
+
+  # Download to a temporary file first
+  tmp_file="$(mktemp)"
+  ensure download "$FOUNDRY_BIN_URL" "$tmp_file"
+
+  # Replace the current foundryup with the downloaded file
+  ensure mv "$tmp_file" "$FOUNDRY_BIN_PATH"
+  ensure chmod +x "$FOUNDRY_BIN_PATH"
+
+  say "successfully updated foundryup"
+  exit 0
+}
+
+list() {
+  if [ -d "$FOUNDRY_VERSIONS_DIR" ]; then
+    for VERSION in $FOUNDRY_VERSIONS_DIR/*; do
+      say "${VERSION##*/}"
+      for bin in "${BINS[@]}"; do
+        bin_path="$VERSION/$bin"
+        say "- $(ensure "$bin_path" -V)"
+      done
+      printf "\n"
+    done
+  else
+    for bin in "${BINS[@]}"; do
+      bin_path="$FOUNDRY_BIN_DIR/$bin"
+      say "- $(ensure "$bin_path" -V)"
+    done
+  fi
+  exit 0
+}
+
+use() {
+  [ -z "$FOUNDRYUP_VERSION" ] && err "no version provided"
+  FOUNDRY_VERSION_DIR="$FOUNDRY_VERSIONS_DIR/$FOUNDRYUP_VERSION"
+  if [ -d "$FOUNDRY_VERSION_DIR" ]; then
+
+    check_bins_in_use
+
+    for bin in "${BINS[@]}"; do
+      bin_path="$FOUNDRY_BIN_DIR/$bin"
+      cp "$FOUNDRY_VERSION_DIR/$bin" "$bin_path"
+      # Print usage msg
+      say "use - $(ensure "$bin_path" -V)"
+
+      # Check if the default path of the binary is not in FOUNDRY_BIN_DIR
+      which_path="$(command -v "$bin" || true)"
+      if [ -n "$which_path" ] && [ "$which_path" != "$bin_path" ]; then
+        warn ""
+        cat 1>&2 <<EOF
+There are multiple binaries with the name '$bin' present in your 'PATH'.
+This may be the result of installing '$bin' using another method,
+like Cargo or other package managers.
+You may need to run 'rm $which_path' or move '$FOUNDRY_BIN_DIR'
+in your 'PATH' to allow the newly installed version to take precedence!
+
+EOF
+      fi
+    done
+    exit 0
+  else
+    err "version $FOUNDRYUP_VERSION not installed"
+  fi
 }
 
 say() {
@@ -368,6 +465,18 @@ need_cmd() {
 
 check_cmd() {
   command -v "$1" &>/dev/null
+}
+
+check_bins_in_use() {
+  if check_cmd pgrep; then
+    for bin in "${BINS[@]}"; do
+      if pgrep -x "$bin" >/dev/null; then
+        err "Error: '$bin' is currently running. Please stop the process and try again."
+      fi
+    done
+  else
+    warn "Make sure no foundry process is running during the install process!"
+  fi
 }
 
 # Run a command that should never fail. If the command fails execution
